spring.application.name=usp

# ==========================================
# 1. CONEXÃO COM A BASE DE DADOS (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Otimização do Pool de Conexões (HikariCP - Padrão do Spring Boot)
# Evita sobrecarregar o banco e define timeouts seguros
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

# ==========================================
# 2. CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logs de SQL limpos e legíveis
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Otimização de performance para inserts/updates em lote (Batching)
# Excelente para quando o teu ERP precisar de salvar muitos dados de uma vez
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


# ==========================================
# 3. INTERNACIONALIZAÇÃO E PARSING
# ==========================================
# Garante que as datas enviadas pelo banco/JSON não fiquem com fusos horários malucos
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

# ==========================================
# 4. INICIALIZAÇÃO POR SCRIPT SQL
# ==========================================
# Ativa a execução do schema.sql sempre que a aplicação inicia
#spring.sql.init.mode=always
#spring.sql.init.separator=$$

# Garante que o Spring cria a estrutura do script ANTES do Hibernate validar as entidades
spring.jpa.defer-datasource-initialization=false

# Se falhar porque a tabela já existe, evita que a aplicação vá abaixo
spring.sql.init.continue-on-error=true

# ==========================================
# 5. CONFIGURAÇÃO DE SEGURANÇA (JWT SUPABASE)
# ==========================================
# Use exatamente a mesma chave que definiu no seu ficheiro .env do Docker
spring.security.oauth2.resourceserver.jwt.secret-key=rDOQoFCGX1yH5upVjzewKvI9c64S2EdYlRTBbhZUqWsLMxft3n780gkPaimJAN

# Caminho dentro do contentor Docker onde os ficheiros vão cair
file.upload-dir=/app/uploads

# Permitir upload de ficheiros maiores (Ex: até 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB