name: Build and Publish usp-frontend

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - frontend-release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tetrasoft-dev/usp-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Test frontend repository access
        env:
            FRONTEND_TOKEN: ${{ secrets.FRONTEND_REPO_TOKEN }}
        run: |
            STATUS=$(curl -sS \
            -o /tmp/repo.json \
            -w "%{http_code}" \
            -H "Authorization: Bearer $FRONTEND_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Ademilicia95/sistema-gestao-artigos)

            echo "HTTP Status: $STATUS"

            if [ "$STATUS" != "200" ]; then
            echo "ERRO: o token nao consegue acessar o repositorio do frontend."
            cat /tmp/repo.json
            exit 1
            fi

            echo "Acesso ao repositorio do frontend confirmado."

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: Ademilicia95/sistema-gestao-artigos
          token: ${{ secrets.FRONTEND_REPO_TOKEN }}
          path: frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true

          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ vars.FRONTEND_BACKEND_URL }}
            NEXT_PUBLIC_SUPABASE_URL=${{ vars.FRONTEND_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.FRONTEND_SUPABASE_ANON_KEY }}
            SUPABASE_GOTRUE_URL=${{ vars.FRONTEND_AUTH_URL }}

          tags: |
            ghcr.io/tetrasoft-dev/usp-frontend:latest
            ghcr.io/tetrasoft-dev/usp-frontend:${{ github.sha }}